name: CI / CD

on:
  push:
    branches: [main]

jobs: Build-and-Deploy
  runs-on: ubuntu-latest

  steps:
  - name: Cloner le dépôt
    uses: actions/checkout@v2

  - name: Installer Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '18'

  - name: Installer les dépendances
    run: npm install

  

  - name: deploiment sur un VPS avec SSH
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USER }}
      key: ${{ secrets.SSH_KEY }}
      port: ${{ secrets.SSH_PORT }}
      script: |
        cd ~/workflow || mkdir ~/workflow && cd ~/workflow
        git clone https://github.com/${{ github.repository }}.git . || git pull
        npm install
        pm2 delete my_api_node || true
        pm2 start index.js --name my_api_node
        pm2 save
        pm2 list